sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.6.1
  - 2.6.3
before_install:
  - gem update --system
  - sudo apt-get update && sudo apt-get install libsodium18
gemfile: test/support/dummy_api/Gemfile
env:
  - RAILS_VERSION="~> 5.1"
  - RAILS_VERSION="~> 5.2"
  - RAILS_VERSION="~> 6.0"
services:
  - redis-server
